---
name: HideCommands
version: 2.0.2
main: Himbeer\HideCommands\Main
api: 4.0.0
mcpe-protocol:
  - 475 # v1.18.0
  - 486 # v1.18.10
  - 503 # v1.18.30
  - 527 # v1.19.0
  - 534 # v1.19.10
author: Himbeer
website: himbeer.me
description: Remove specific commands from the in-game command suggestions.

permissions:
  hidecommands.unhide:
    description: "Players with this permission can see all commands"
    default: false
...
