---
name: HideCommands
version: 3.0.3
main: Himbeer\HideCommands\Main
api:
  - 4.4.0
  - 5.0.0
mcpe-protocol:
  - 475 # v1.18.0
  - 486 # v1.18.10
  - 503 # v1.18.30
  - 527 # v1.19.0
  - 534 # v1.19.10
  - 544 # v1.19.20
  - 545 # v1.19.21
  - 554 # v1.19.30
  - 557 # v1.19.40
  - 560 # v1.19.50
  - 567 # v1.19.60
  - 575 # v1.19.70
  - 582 # v1.19.80
  - 589 # v1.20.0
author: Himbeer
website: himbeer.me
description: Remove specific commands from the in-game command suggestions.

permissions:
  hidecommands.unhide:
    description: "Players with this permission can see all commands"
    default: false
...
